version: "3.8"
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=race
    volumes:
      - postgres-data:/var/lib/postgresql/data

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
  
  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CREATE_TOPICS: "races:1:3,applications:1:3"
      KAFKA_OFFSETS_RETENTION_MINUTES: 60

   race-query-service:
    build:
      context: ./race_query_service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      KAFKA_BOOTSTRAP_SERVER: kafka:9092
      POSTGRES_URL: postgres
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: race
    depends_on:
      - postgres
      - kafka

   race-command-service:
    build:
      context: ./race_command_service
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      KAFKA_BOOTSTRAP_SERVER: kafka:9092
      RACE_QUERY_GATEWAY: http://race-query-service:8080/api/v1/users/{username}
    depends_on:
      - kafka
      - race-query-service
    
   race-app-client-app:
    build:
      context: ./race-application-client-application
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - race-query-service
      - race-command-service
      
volumes:
  postgres-data:
