CREATE TABLE race (
    id UUID PRIMARY KEY NOT NULL,
    name VARCHAR(255) NOT NULL,
    distance VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);