CREATE TYPE race_distance AS ENUM ('FIVEKM', 'TENKM', 'HALFMARATHON', 'MARATHON');

CREATE TABLE race (
    id UUID PRIMARY KEY NOT NULL,
    name VARCHAR(255) NOT NULL,
    distance race_distance NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);